{% set name = "colorcet" %}
{% set version = "2.0.5" %}
{% set sha256 = "2246ad5e09f37834a3225bf20ccb2700bc565018f133a1ff3d86bb0fdb7fee5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools >=30.3.0
    - param >=1.7.0
    - pyct >=0.4.4
    - wheel

  run:
    - python >=2.7
    - param >=1.7.0
    - pyct >=0.4.4

test:
  imports:
    - colorcet

about:
  home: http://github.com/pyviz/colorcet
  license: CC-BY-4.0
  license_file: LICENSE.txt
  summary: Collection of perceptually uniform colormaps

extra:
  recipe-maintainers:
    - jbednar
    - jsignell
