{% set name = "colorcet" %}
{% set version = "3.0.1" %}
{% set sha256 = "51455a20353d12fac91f953772d8409f2474e6a0db1af3fa4f7005f405a2480b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools >=30.3.0
    - pyct >=0.4.4
    - wheel

  run:
    - python >=2.7
    - pyct >=0.4.4

test:
  imports:
    - colorcet

about:
  home: http://github.com/pyviz/colorcet
  license: CC-BY-4.0
  license_file: LICENSE.txt
  summary: Collection of perceptually uniform colormaps

extra:
  recipe-maintainers:
    - maximlt
    - droumis
    - jbednar
    - jsignell
