{% set name = "colorcet" %}
{% set version = "3.1.0" %}
{% set sha256 = "2921b3cd81a2288aaf2d63dbc0ce3c26dcd882e8c389cc505d6886bf7aa9a4eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools >=30.3.0
    - pyct >=0.4.4
    - wheel

  run:
    - python >=2.7
    - pyct >=0.4.4

test:
  imports:
    - colorcet

about:
  home: http://github.com/pyviz/colorcet
  license: CC-BY-4.0
  license_file: LICENSE.txt
  summary: Collection of perceptually uniform colormaps

extra:
  recipe-maintainers:
    - droumis
    - jbednar
    - jsignell
